export type BarcodeOverride =
  | {
      kind: "movie";
      tmdbId: number;
      title: string;
      year: number;
      packageTitle: string;
      editionLabel?: string;
      formats: string[];
      discCount: number;
      digitalCodeExpected?: boolean | null;
      slipcoverExpected?: boolean | null;
    }
  | {
      kind: "multi_movie";
      productTitle: string;
      collectionName?: string;
      editionLabel?: string;
      movieTmdbIds: number[];
      formats: string[];
      discCount: number;
      digitalCodeExpected?: boolean | null;
      slipcoverExpected?: boolean | null;
    }
  | {
      kind: "tv_box_set";
      productTitle: string;
      showName: string;
      tmdbSeriesId: number;
      seasonNumbers: number[];
      formats: string[];
      discCount: number;
      editionLabel?: string;
      digitalCodeExpected?: boolean | null;
      slipcoverExpected?: boolean | null;
    };

export const BARCODE_OVERRIDES: Record<string, BarcodeOverride> = {
  "043396544093": {
    kind: "movie",
    tmdbId: 9800,
    title: "Philadelphia",
    year: 1993,
    packageTitle: "Philadelphia (25th Anniversary Edition) (4K Ultra HD + Blu-ray + Digital)",
    editionLabel: "25th Anniversary Edition",
    formats: ["4K", "Blu-ray", "Digital"],
    discCount: 2,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "012236203445": {
    kind: "movie",
    tmdbId: 11967,
    title: "Young Guns",
    year: 1988,
    packageTitle: "Young Guns (Blu-ray)",
    editionLabel: "Blu-ray",
    formats: ["Blu-ray"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "683904630162": {
    kind: "multi_movie",
    productTitle: "Spaghetti Western Double Feature: The Last Gun / 4 Dollars of Revenge (Blu-ray)",
    collectionName: "Spaghetti Western Double Feature",
    editionLabel: "Double Feature",
    movieTmdbIds: [67212, 67213],
    formats: ["Blu-ray"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "683904632197": {
    kind: "movie",
    tmdbId: 849,
    title: "Krull",
    year: 1983,
    packageTitle: "Krull (Blu-ray)",
    editionLabel: "Blu-ray",
    formats: ["Blu-ray"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "883929789702": {
    kind: "multi_movie",
    productTitle: "The Matrix 4-Film Déjà Vu Collection (Blu-ray)",
    collectionName: "The Matrix Collection",
    editionLabel: "4-Film Déjà Vu Collection",
    movieTmdbIds: [603, 604, 605, 624860],
    formats: ["Blu-ray", "Digital"],
    discCount: 4,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "191329047576": {
    kind: "multi_movie",
    productTitle: "The Mummy Trilogy (Blu-ray + Digital HD)",
    collectionName: "The Mummy Collection",
    editionLabel: "Trilogy",
    movieTmdbIds: [564, 1734, 1735],
    formats: ["Blu-ray", "Digital"],
    discCount: 3,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "786936726695": {
    kind: "movie",
    tmdbId: 1124,
    title: "The Prestige",
    year: 2006,
    packageTitle: "The Prestige (Blu-ray)",
    editionLabel: "Blu-ray",
    formats: ["Blu-ray"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "024543234364": {
    kind: "movie",
    tmdbId: 1495,
    title: "Kingdom of Heaven",
    year: 2005,
    packageTitle: "Kingdom of Heaven (Blu-ray + DVD)",
    editionLabel: "Blu-ray + DVD",
    formats: ["Blu-ray", "DVD"],
    discCount: 2,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "786936858648": {
    kind: "movie",
    tmdbId: 10439,
    title: "Hocus Pocus",
    year: 1993,
    packageTitle: "Hocus Pocus (25th Anniversary Edition) (Blu-ray + Digital Copy)",
    editionLabel: "25th Anniversary Edition",
    formats: ["Blu-ray", "Digital"],
    discCount: 1,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "786936893144": {
    kind: "movie",
    tmdbId: 550988,
    title: "Free Guy",
    year: 2021,
    packageTitle: "Free Guy (Blu-ray + Digital)",
    editionLabel: "Blu-ray + Digital",
    formats: ["Blu-ray", "Digital"],
    discCount: 1,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "024543005568": {
    kind: "movie",
    tmdbId: 112205,
    title: "The Family",
    year: 2013,
    packageTitle: "The Family (Blu-ray + DVD + Digital HD)",
    editionLabel: "Blu-ray + DVD + Digital HD",
    formats: ["Blu-ray", "DVD", "Digital"],
    discCount: 2,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "024543435358": {
    kind: "movie",
    tmdbId: 162,
    title: "Edward Scissorhands",
    year: 1990,
    packageTitle: "Edward Scissorhands (Blu-ray)",
    editionLabel: "Blu-ray",
    formats: ["Blu-ray"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "025192108310": {
    kind: "movie",
    tmdbId: 4982,
    title: "American Gangster",
    year: 2007,
    packageTitle: "American Gangster (Unrated) (Blu-ray + DVD)",
    editionLabel: "Unrated",
    formats: ["Blu-ray", "DVD"],
    discCount: 2,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "191329226674": {
    kind: "movie",
    tmdbId: 675353,
    title: "Sonic the Hedgehog 2",
    year: 2022,
    packageTitle: "Sonic the Hedgehog 2 (Blu-ray + Digital Code)",
    editionLabel: "Blu-ray + Digital Code",
    formats: ["Blu-ray", "Digital"],
    discCount: 1,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "024543930020": {
    kind: "movie",
    tmdbId: 193610,
    title: "The Other Woman",
    year: 2014,
    packageTitle: "The Other Woman (Blu-ray + Digital HD)",
    editionLabel: "Blu-ray + Digital HD",
    formats: ["Blu-ray", "Digital"],
    discCount: 1,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "191329144671": {
    kind: "multi_movie",
    productTitle: "Back to the Future: The Ultimate Trilogy (Blu-ray + Digital Code)",
    collectionName: "Back to the Future Collection",
    editionLabel: "Ultimate Trilogy",
    movieTmdbIds: [105, 165, 196],
    formats: ["Blu-ray", "Digital"],
    discCount: 4,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "024543744719": {
    kind: "movie",
    tmdbId: 10140,
    title: "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    year: 2010,
    packageTitle: "The Chronicles of Narnia: The Voyage of the Dawn Treader (Blu-ray + DVD)",
    editionLabel: "Blu-ray + DVD",
    formats: ["Blu-ray", "DVD"],
    discCount: 2,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "786936858136": {
    kind: "movie",
    tmdbId: 299536,
    title: "Avengers: Infinity War",
    year: 2018,
    packageTitle: "Avengers: Infinity War (Blu-ray + Digital Code)",
    editionLabel: "Blu-ray + Digital Code",
    formats: ["Blu-ray", "Digital"],
    discCount: 1,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "786936856330": {
    kind: "movie",
    tmdbId: 284054,
    title: "Black Panther",
    year: 2018,
    packageTitle: "Black Panther (Blu-ray + Digital Code)",
    editionLabel: "Blu-ray + Digital Code",
    formats: ["Blu-ray", "Digital"],
    discCount: 1,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "883929774685": {
    kind: "movie",
    tmdbId: 791373,
    title: "Zack Snyder's Justice League",
    year: 2021,
    packageTitle: "Zack Snyder's Justice League (Blu-ray)",
    editionLabel: "Blu-ray",
    formats: ["Blu-ray"],
    discCount: 2,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "794051400123": {
    kind: "tv_box_set",
    productTitle: "Planet Earth: The Complete Series (Blu-ray)",
    showName: "Planet Earth",
    tmdbSeriesId: 1044,
    seasonNumbers: [1],
    formats: ["Blu-ray"],
    discCount: 4,
    editionLabel: "Complete Series",
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "191329118641": {
    kind: "movie",
    tmdbId: 670266,
    title: "Tremors: Shrieker Island",
    year: 2020,
    packageTitle: "Tremors: Shrieker Island (DVD)",
    editionLabel: "DVD",
    formats: ["DVD"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "014381514926": {
    kind: "movie",
    tmdbId: 14541,
    title: "Jeff Dunham's Very Special Christmas Special",
    year: 2008,
    packageTitle: "Jeff Dunham's Very Special Christmas Special (DVD)",
    editionLabel: "DVD",
    formats: ["DVD"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: false,
  },
  "032429327550": {
    kind: "movie",
    tmdbId: 504608,
    title: "Rocketman",
    year: 2019,
    packageTitle: "Rocketman (Blu-ray)",
    editionLabel: "Blu-ray",
    formats: ["Blu-ray"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "043396581593": {
    kind: "movie",
    tmdbId: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    year: 2023,
    packageTitle: "Spider-Man: Across the Spider-Verse (Blu-ray + DVD + Digital Code)",
    editionLabel: "Blu-ray + DVD + Digital Code",
    formats: ["Blu-ray", "DVD", "Digital"],
    discCount: 2,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "031398272274": {
    kind: "multi_movie",
    productTitle: "The Divergent Series: Divergent / Insurgent / Allegiant (Blu-ray + Digital)",
    collectionName: "Divergent Collection",
    editionLabel: "3-Film Collection",
    movieTmdbIds: [157350, 262500, 262504],
    formats: ["Blu-ray", "Digital"],
    discCount: 3,
    digitalCodeExpected: true,
    slipcoverExpected: null,
  },
  "032429243775": {
    kind: "multi_movie",
    productTitle: "Star Trek II, III, IV Motion Picture Trilogy (Blu-ray)",
    collectionName: "Star Trek II, III, IV Collection",
    editionLabel: "Motion Picture Trilogy",
    movieTmdbIds: [154, 157, 168],
    formats: ["Blu-ray"],
    discCount: 3,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "013132612102": {
    kind: "tv_box_set",
    productTitle: "Spartacus: War of the Damned - The Complete Third Season (Blu-ray)",
    showName: "Spartacus",
    tmdbSeriesId: 25287,
    seasonNumbers: [3],
    formats: ["Blu-ray"],
    discCount: 3,
    editionLabel: "Best Buy Exclusive",
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "013132309491": {
    kind: "tv_box_set",
    productTitle: "Spartacus: Gods of the Arena (DigiBook Blu-ray)",
    showName: "Spartacus: Gods of the Arena",
    tmdbSeriesId: 35948,
    seasonNumbers: [1],
    formats: ["Blu-ray"],
    discCount: 2,
    editionLabel: "DigiBook",
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "883929174096": {
    kind: "tv_box_set",
    productTitle: "Human Planet: The Complete Series (BBC Blu-ray)",
    showName: "Human Planet",
    tmdbSeriesId: 35787,
    seasonNumbers: [1],
    formats: ["Blu-ray"],
    discCount: 3,
    editionLabel: "Complete Series",
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "025192064470": {
    kind: "multi_movie",
    productTitle: "The Bourne Trilogy: The Bourne Identity / The Bourne Supremacy / The Bourne Ultimatum (Blu-ray)",
    collectionName: "The Bourne Collection",
    editionLabel: "Trilogy",
    movieTmdbIds: [2501, 2502, 2503],
    formats: ["Blu-ray"],
    discCount: 3,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "794043702020": {
    kind: "multi_movie",
    productTitle: "Teenage Mutant Ninja Turtles 3-Pak (TMNT / Secret of the Ooze / TMNT III) (DVD)",
    collectionName: "Teenage Mutant Ninja Turtles Collection",
    editionLabel: "3-Pak",
    movieTmdbIds: [1498, 1499, 1500],
    formats: ["DVD"],
    discCount: 3,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "024543456896": {
    kind: "multi_movie",
    productTitle: "Alien Quadrilogy: Alien / Aliens / Alien 3 / Alien Resurrection (Blu-ray)",
    collectionName: "Alien Collection",
    editionLabel: "Quadrilogy",
    movieTmdbIds: [348, 679, 8077, 8078],
    formats: ["Blu-ray"],
    discCount: 4,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "024543982852": {
    kind: "multi_movie",
    productTitle: "AVP Double Feature: Alien vs. Predator / Aliens vs. Predator: Requiem (DVD)",
    collectionName: "Alien vs. Predator Collection",
    editionLabel: "Double Feature",
    movieTmdbIds: [395, 440],
    formats: ["DVD"],
    discCount: 2,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "786936827682": {
    kind: "multi_movie",
    productTitle: "Atlantis 2-Movie Collection: The Lost Empire / Milo's Return (Blu-ray + DVD)",
    collectionName: "Atlantis Collection",
    editionLabel: "2-Movie Collection",
    movieTmdbIds: [10865, 16242],
    formats: ["Blu-ray", "DVD"],
    discCount: 3,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "191329016206": {
    kind: "tv_box_set",
    productTitle: "The Expanse: Season Two (Blu-ray)",
    showName: "The Expanse",
    tmdbSeriesId: 63639,
    seasonNumbers: [2],
    formats: ["Blu-ray"],
    discCount: 3,
    editionLabel: "Season Two",
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "025192342738": {
    kind: "tv_box_set",
    productTitle: "The Expanse: Season One (Blu-ray)",
    showName: "The Expanse",
    tmdbSeriesId: 63639,
    seasonNumbers: [1],
    formats: ["Blu-ray"],
    discCount: 3,
    editionLabel: "Season One",
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "883929590445": {
    kind: "tv_box_set",
    productTitle: "Doctor Who: Series 10 - Part 1 (DVD)",
    showName: "Doctor Who",
    tmdbSeriesId: 57243,
    seasonNumbers: [10],
    formats: ["DVD"],
    discCount: 2,
    editionLabel: "Series 10 - Part 1",
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "883929590469": {
    kind: "tv_box_set",
    productTitle: "Doctor Who: Series 10 - Part 2 (DVD)",
    showName: "Doctor Who",
    tmdbSeriesId: 57243,
    seasonNumbers: [10],
    formats: ["DVD"],
    discCount: 2,
    editionLabel: "Series 10 - Part 2",
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "085391174301": {
    kind: "multi_movie",
    productTitle: "Lethal Weapon: 4 Film Favorites (DVD)",
    collectionName: "Lethal Weapon Collection",
    editionLabel: "4 Film Favorites",
    movieTmdbIds: [941, 942, 943, 944],
    formats: ["DVD"],
    discCount: 4,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
  "013131140699": {
    kind: "movie",
    tmdbId: 3355,
    title: "SpaceCamp",
    year: 1986,
    packageTitle: "SpaceCamp (DVD)",
    editionLabel: "Special Edition",
    formats: ["DVD"],
    discCount: 1,
    digitalCodeExpected: false,
    slipcoverExpected: null,
  },
};
